2020-05-16 21:42:24,968 ERROR 18840 [-/111.198.226.92/-/5026ms GET /news] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://hacker-news.firebaseio.com/v0/topstories.json -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/root/design-platform/node_modules/urllib/lib/urllib.js:938:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ConnectionTimeoutError"
requestId: 1
data: undefined
path: "/v0/topstories.json?orderBy=%22%24key&startAt=%220%22&endAt=%224%22"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":5017,"keepAliveSocket":false,"requestUrls":["https://hacker-news.firebaseio.com/v0/topstories.json"],"timing":null,"remoteAddress":"35.201.97.85","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 18840
hostname: iZ8vbcval6t2nfh7e1q5q2Z

2020-05-16 21:49:24,452 ERROR 18854 [-/111.198.226.92/-/5024ms GET /news] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://hacker-news.firebaseio.com/v0/topstories.json -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/root/design-platform/node_modules/urllib/lib/urllib.js:938:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ConnectionTimeoutError"
requestId: 1
data: undefined
path: "/v0/topstories.json?orderBy=%22%24key&startAt=%220%22&endAt=%224%22"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":5015,"keepAliveSocket":false,"requestUrls":["https://hacker-news.firebaseio.com/v0/topstories.json"],"timing":null,"remoteAddress":"35.201.97.85","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 18854
hostname: iZ8vbcval6t2nfh7e1q5q2Z

2020-05-18 21:25:52,184 ERROR 22343 [-/111.198.228.14/-/206ms GET /news] nodejs.RequestError: getaddrinfo ENOTFOUND topstories.json topstories.json:80, GET http:///topstories.json -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"topstories.json:80:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {} (topstories.json)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
errno: "ENOTFOUND"
code: "ENOTFOUND"
syscall: "getaddrinfo"
hostname: "topstories.json"
host: "topstories.json"
port: 80
name: "RequestError"
data: undefined
path: "/?orderBy=%22%24key&startAt=%220%22&endAt=%224%22"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":197,"keepAliveSocket":false,"requestUrls":["http://topstories.json/"],"timing":null,"remoteAddress":"","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 22343
hostname: iZ8vbcval6t2nfh7e1q5q2Z

2020-05-18 21:26:22,475 ERROR 22365 [-/111.198.228.14/-/51ms GET /news] nodejs.RequestError: getaddrinfo ENOTFOUND topstories.json topstories.json:80, GET http:///topstories.json -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"topstories.json:80:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {} (topstories.json)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
errno: "ENOTFOUND"
code: "ENOTFOUND"
syscall: "getaddrinfo"
hostname: "topstories.json"
host: "topstories.json"
port: 80
name: "RequestError"
data: undefined
path: "/?orderBy=%22%24key&startAt=%220%22&endAt=%224%22"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":41,"keepAliveSocket":false,"requestUrls":["http://topstories.json/"],"timing":null,"remoteAddress":"","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 22365
hostname: iZ8vbcval6t2nfh7e1q5q2Z

2020-06-18 19:48:46,922 ERROR 24771 [-/undefined/-/27ms GET /public/static/index.js] nodejs.EPIPEError: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
errno: "EPIPE"
code: "EPIPE"
syscall: "write"
headerSent: true
name: "EPIPEError"
pid: 24771
hostname: MacBook-Pro-2.local

2020-06-18 19:57:16,498 ERROR 28707 [-/undefined/-/19ms GET /public/static/index.js] nodejs.EPIPEError: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
errno: "EPIPE"
code: "EPIPE"
syscall: "write"
headerSent: true
name: "EPIPEError"
pid: 28707
hostname: MacBook-Pro-2.local

2020-06-18 21:15:24,848 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 1212599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 21:36:20,475 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 1215602ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 21:51:51,148 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 910662ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 22:03:59,505 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 708346ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 22:14:15,832 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 575501ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 22:24:11,335 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 575498ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 22:55:34,018 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 1862660ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:05:17,435 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 583375ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:15:36,518 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:25:54,714 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:35:54,476 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579702ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:46:12,343 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 577824ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-18 23:56:11,945 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579564ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:06:31,793 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579795ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:16:35,938 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 584097ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:26:54,568 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578575ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:36:54,818 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 580215ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:47:13,279 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578396ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 00:57:14,947 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581634ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:07:32,851 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 577793ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:17:51,166 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578171ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:27:50,042 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578674ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:38:09,454 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579153ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:48:08,352 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 01:58:27,558 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578928ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:08:31,256 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 583378ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:18:48,958 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 577308ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:28:50,864 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581442ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:39:09,988 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578187ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:49:12,863 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 582358ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 02:59:32,763 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579280ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 03:09:34,843 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581632ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 03:19:53,885 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578345ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 03:29:54,941 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 580637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 03:40:15,436 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 580011ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 03:50:16,003 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 580163ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:00:34,964 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578359ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:10:40,004 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 584620ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:20:58,442 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578176ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:30:58,005 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579228ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:41:17,251 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 04:51:18,997 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581123ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:01:37,132 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 577708ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:11:38,972 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581363ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:21:57,951 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578352ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:31:57,853 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:42:16,845 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578182ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 05:52:19,054 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 581515ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:02:38,925 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579346ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:12:42,076 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 582780ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:23:00,116 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 577477ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:33:04,009 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 583422ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:43:24,180 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 579771ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 06:53:24,967 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 580609ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 07:03:44,158 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 578927ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 07:13:47,006 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 582572ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 08:33:25,317 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 4737850ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-06-19 08:51:07,650 ERROR 24770 nodejs.ClusterClientNoResponseError: client no response in 1022306ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lingyun/Work/design-platform/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 24770
hostname: MacBook-Pro-2.local

2020-07-28 21:35:21,759 ERROR 46443 [-/undefined/-/82ms GET /public/static/index.js] nodejs.EPIPEError: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
errno: "EPIPE"
code: "EPIPE"
syscall: "write"
headerSent: true
name: "EPIPEError"
pid: 46443
hostname: 192.168.0.102

2020-07-28 21:35:21,958 ERROR 46443 [-/undefined/-/140ms GET /public/static/index.js] nodejs.EPIPEError: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
errno: "EPIPE"
code: "EPIPE"
syscall: "write"
headerSent: true
name: "EPIPEError"
pid: 46443
hostname: 192.168.0.102

